services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  devinsales:
    image: lucasflotaif/devinsales
    container_name: devinsales
    ports:
      - '8080:8080'
    depends_on:
      - db
volumes:
  db:
    driver: local
