version: '2'
services:
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
  devinsales:
    container_name: 'devinsales'
    image: lucasflotaif/devinsales:1.0.0
    ports:
      - '8080:8081'
    depends_on:
      - database
volumes:
  db-data:
    driver: local